[package]
name = "nh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.28"
egui_dock = "0.13"
rfd = "0.14.1"
uuid = { version = "1.10.0", features = [ "std", "v7" ] }
